#%RAML 1.0
title: identity-sys-api
version: 1.0.0
description: This api will be used to create username and password in okta, authenticate customer, reset password, activate and deactivate user.
           
traits:
  responseMessages: !include /exchange_modules/d9d9eb2b-81d3-49a6-87d1-fc6bc8fc5063/responses/1.0.1/responses.raml

types:
  User: !include /resources/datatypes/user-datatype.raml

/customers:
  /createUsernamePaswword:
    displayName: Create User.
    description: This api will create username and password in Okta server.

    post:
      body:
        application/json:
          type: User
          examples:
            input: !include /resources/examples/user-example.raml
      
      responses:
        200:
          body:
            application/json:
              examples:
                output: !include /resources/examples/user-response-example.raml
      is: [responseMessages]
    
  /resetPassword:
    displayName: Reset password.
    description: This api will reset password for the username in Okta server.

    /{userId}:
      description: This userId is the id which is on okta server.

      post:
        responses:
          200:
            body:
              application/json:
                example:
                  message: "Link send to reset the password."
        is: [responseMessages]

  /authenticateUser:
    displayName: Authenticate User
    description: This api will check if user is there in Okta or not.

    /{userId}:
      description: User id is the id returned through Okta.
      get:
        responses:
          200:
            body:
              application/json:
                examples:
                  output: !include /resources/examples/user-response-example.raml
        is: [responseMessages]

  /activateUser:
    displayName: Activate User.
    description: This api will activate the user in Okta server.

    /{userId}:
      description:  This user id is the id returned by the Okta server.
    
      post:
        responses:
          200:
            body:
              application/json:
                example:
                 message: "User activated successfully"
        is: [responseMessages]

  /deactivateUser:
    displayName: Deactivate user
    description: This api will deactivate the user.

    /{userId}:
      description: This api is the id generated by the okta.

      post:
        responses:
          200:
            body:
              application/json:
                example:
                  message: "User deactivated successfully"
        is: [responseMessages]

  /getUserData:
    displayName: Get okta user details.
    description: This api will give the credential details of the user.

    /{userId}:
      description: Userid is the id return by the okta server.  
    
      post:
        responses:
          200:
            body:
              application/json:
                examples:
                  output: !include /resources/examples/user-response-example.raml
        is: [responseMessages]

  /changePassword:
    displayName: Change password.
    description: This api will change password for okta user.

    /{userId}:
      description: Userid is the id return by the okta server.  
      post:
        body:
          application/json:
            example: |
              {
                "oldPassword":  "vikas",
                "newPassword": "Puri"
              }
              
        responses:
          200:
            body:
              application/json:
                example: 
                  message: "Password changed"
        is: [responseMessages]
